// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU6AtaWcCnewA_mUzWnbDSW1BFpzpcU6A',
    appId: '1:10058838350:web:a3fb14c89b93bc87c6ee1f',
    messagingSenderId: '10058838350',
    projectId: 'lista-compras-firebase-21837',
    authDomain: 'lista-compras-firebase-21837.firebaseapp.com',
    storageBucket: 'lista-compras-firebase-21837.firebasestorage.app',
    measurementId: 'G-08PG3HQQK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRlUNHSIG5ceAP36phgN2ijcs4a7v6VP0',
    appId: '1:10058838350:android:a459c0f6488dc444c6ee1f',
    messagingSenderId: '10058838350',
    projectId: 'lista-compras-firebase-21837',
    storageBucket: 'lista-compras-firebase-21837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13svwwCazZLJjIz7P--CA8nOB6FSqgHM',
    appId: '1:10058838350:ios:0f41fb8d823db5afc6ee1f',
    messagingSenderId: '10058838350',
    projectId: 'lista-compras-firebase-21837',
    storageBucket: 'lista-compras-firebase-21837.firebasestorage.app',
    iosBundleId: 'leankar.dev.flutterListaComprasFirebase',
  );
}
